# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ronen Agranat
email: ronen.agranat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website, portfolio and blog of Ronen Agranat, software developer and people manager
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ronenagranat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ronenagranat
github_username:  ronen-agranat
linkedin_username: ronen-agranat
instagram_username: ronenagranat

# jekyll-seo-tag configuration

twitter:
  username: ronenagranat
  card: summary
logo: assets/images/profile.jpg
social:
  name: Ronen Agranat
  links:
    - https://twitter.com/ronenagranat
    - https://www.linkedin.com/in/ronen-agranat
    - https://github.com/ronen-agranat
    - https://facebook.com/ronen.agranat
lang: en_GB

# Comments section
disqus:
  shortname: ronen-agranat

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:year-:month-:day/:title:output_ext

google_analytics: UA-129309201-1

# show_excerpts: true
# excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - commands.sh
  - README.md
